### ISSUE TITLE
Pasting into inputs pastes content twice

### ISSUE THREAD

**Issue by ItsVoltz** [AllenDang/giu#340]
When pasting into a input field it pastes the contents of the clipboard twice

**Comment by AllenDang** [comment]
@ItsVoltz I cannot reproduce it. Try to get the newest code to see if it still happens.

**Comment by ItsVoltz** [comment]
> @ItsVoltz I cannot reproduce it. Try to get the newest code to see if it still happens.

I am on master currently:

https://user-images.githubusercontent.com/29076540/133971898-3865a19a-89a0-4569-a3f1-6eb2328a4bff.mp4

**Comment by AllenDang** [comment]
@ItsVoltz What os you are using? I still cannot repo on Win10 and macOS

**Comment by ItsVoltz** [comment]
> @ItsVoltz What os you are using? I still cannot repo on Win10 and macOS

Windows 10

**Comment by ItsVoltz** [comment]
Bump any idea for fix?

**Comment by AllenDang** [comment]
@ItsVoltz Sorry, still cannot find the way to repo it.

**Comment by ItsVoltz** [comment]
> @ItsVoltz Sorry, still cannot find the way to repo it.

Here is the code for my login inputs, I'm just so confused as to why It pastes twice

```go
g.Align(g.AlignCenter).To(
				g.Row(
					g.Dummy(0, 0),
					g.InputText(&cl.fields.username).Size(280).Hint("Username"),
				),
				g.Row(
					g.Dummy(0, 0),
					g.InputText(&cl.fields.password).Flags(g.InputTextFlagsPassword).Size(280).Hint("Password"),
				),
			),
```

**Comment by gucio321** [comment]
hmm, interessting, seems like my fault again :grinning:

AlignSetter is a kind of beta solution, because it is (in fact) not supported by imgui. So @ItsVoltz if you know the width of InputTextWidget, I'd recommend you to use Dummy to align it:
<details><summary>code</summary>

```golang
const inputTextW = 280
giu.Custom(func() {
      availableW, _ := giu.GetAvailableRegion()
      giu.Dummy((availableW-inputTextW)/2,0).Build()
      g.InputText(&cl.fields.username).Size(inputTextW).Hint("Username").Build()
}),
```

</details>

However it is a bug in AlignSetter and it should be fixed.
<details><summary>example of the bug</summary>

```golang
package main

import g "github.com/AllenDang/giu"

var username, password string

func loop() {
	g.SingleWindow().Layout(
		g.Align(g.AlignCenter).To(
			g.Row(
				g.InputText(&username).Size(280).Hint("Username"),
			),
			g.Row(
				g.InputText(&password).Flags(g.InputTextFlagsPassword).Size(280).Hint("Password"),
			),
		),
	)
}

func main() {
	wnd := g.NewMasterWindow("demo", 640, 480, 0)
	wnd.Run(loop)
}
```

</details>

## reason

giu renders each widget twice. first in alpha = 0.
Because these widgets has the same ID, both gets highlighted when you focus this visible one.
It seems that if you paste the text, it is `pasted` for each widget (this visible an this hidden).
You are most likely to see it in the following demo:
```golang
        w := g.InputText(&username)
        g.SingleWindow().Layout(
                w,
                w,
        )
```

## solution

currently no idea.

**Comment by gucio321** [comment]
## solution
what about
```golang
func GetWidgetWidth(w Widget) float32 {
// ...
imgui.PushID(fmt.Sprintf("##GetWidgetWidth%d", widgetWidthCounter)
widgetWidthCounter++
// do width measurement
imgui.PopID()
```

I'd suggest to use a separated fro giu's one auto id counter, because GetWidgetWidth can be randomly called and may destroy some layouts (see #346)

**Comment by gucio321** [comment]
ok, it may works, but I met another issue - the invisible widget covers the visible one so that it isn't able to click.

**Comment by ItsVoltz** [comment]
I have tried manually centering the inputs (which not being in align does indeed fix the pasting issue): However doesn't seem to center it correctly, as ill mention again align doesn't align properly to the center, as you can see in this image here:
![image](https://user-images.githubusercontent.com/29076540/134778270-3b9d1ef8-c068-4b0a-abac-66f04267db31.png)


Code:
``` go
			g.Custom(func() {
				aW, _ := g.GetAvailableRegion()
				g.Row(
					g.Dummy((aW-widgetWidth)/2, 0),
					g.InputText(&cl.fields.username).Size(280).Hint("Username"),
				).Build()
			}),
```

**Comment by gucio321** [comment]
must be something with item spacing. I'll take a look.

**Comment by gucio321** [comment]
ok, got it. GetCursorPos returns absolute cursor position in window, when GetAvailableRegion returns the region considering window padding value. I'll open a PR to fix it.

**Comment by gucio321** [comment]
@ItsVoltz could you try now, it should be fixed.

**Comment by ItsVoltz** [comment]
> @ItsVoltz could you try now, it should be fixed.

![image](https://user-images.githubusercontent.com/29076540/135114938-5aafe086-c7cc-45fd-a30f-a663b1b852f5.png)

Cannot compile with latest

**Comment by gucio321** [comment]
@ItsVoltz yah, the paste bug isn't fixed yet, I just wanted you to check if centering works now
btw in case of DPI see here: https://github.com/AllenDang/giu/issues/350
IMO it isn't necessary any more?...

**Comment by ItsVoltz** [comment]
> @ItsVoltz yah, the paste bug isn't fixed yet, I just wanted you to check if centering works now btw in case of DPI see here: #350 IMO it isn't necessary any more?...

Should it work with buttons now??

**Comment by gucio321** [comment]
yah, the issue described in yout comment above (https://github.com/AllenDang/giu/issues/340#issuecomment-927143287) should work now

**Comment by ItsVoltz** [comment]
> yah, the issue described in yout comment above ([#340 (comment)](https://github.com/AllenDang/giu/issues/340#issuecomment-927143287)) should work now

still broken

**Comment by gucio321** [comment]
hmm, I think that now alignSetter works good, but the workaround, I suggested is wrong.
lets look at my demo:
![image](https://user-images.githubusercontent.com/73652197/135132904-4221fd51-bf53-4a29-a269-7af42e5f803b.png)
the first input is aligned using workaround code, second - with AlignSetter.
<detailis><summary>code</summary>

```golang
package main

import (
	g "github.com/AllenDang/giu"
)

var username string

const widgetWidth = 280

func loop() {
	// spacing, _ := g.GetItemSpacing()
	g.Window("wnd").Layout(
		g.Custom(func() {
			aW, _ := g.GetAvailableRegion()
			g.Row(
				g.Dummy((aW-widgetWidth)/2, 0),
				g.InputText(&username).Size(widgetWidth).Hint("Username"),
			).Build()
		}),
		g.Align(g.AlignCenter).To(
			g.Row(
				g.InputText(&username).Size(widgetWidth).Hint("Username"),
			)),
		/*
			g.Custom(func() {
				aW, _ := g.GetAvailableRegion()
				g.Row(
					g.Dummy((aW-widgetWidth)/2, 0),
					g.InputText(&username).Size(widgetWidth).Hint("Username"),
				).Build()
			}),
			g.Align(g.AlignCenter).To(
				g.Row(
					g.Button("Login").Size((widgetWidth-spacing)/2, 25),
					g.Button("Exit").Size((widgetWidth-spacing)/2, 25),
				)),
		*/
	)
}

func main() {
	wnd := g.NewMasterWindow("Hello world", 400, 200, 0)
	wnd.Run(loop)
}
```

</details>

My guss is, that in the RowWidget, between the Dummy and InputText, imgui places a separator (ItemSpacing), so:
```golang
                g.Custom(func() {
                        aW, _ := g.GetAvailableRegion()
                        spacing, _ := g.GetItemSpacing()
                        g.Row(
                                g.Dummy((aW-widgetWidth)/2-spacing, 0),
                                g.InputText(&username).Size(widgetWidth).Hint("Username"),
                        ).Build()
                }),
```

**Comment by ItsVoltz** [comment]
@AllenDang @gucio321 pasting into inputs still does not work, any ETA when this will be fixed its been nearly 2 months

**Comment by AllenDang** [comment]
@ItsVoltz Sorry, I thought this issue is closed. I'll take a look now.

**Comment by AllenDang** [comment]
@ItsVoltz I suggest not to use `Align` at this point, manual calcuate the position and center them instead.

**Comment by gucio321** [comment]
> ## solution
> what about
> ```golang
> func GetWidgetWidth(w Widget) float32 {
> // ...
> imgui.PushID(fmt.Sprintf("##GetWidgetWidth%d", widgetWidthCounter)
> widgetWidthCounter++
> // do width measurement
> imgui.PopID()
> ```
> 
> I'd suggest to use a separated fro giu's one auto id counter, because GetWidgetWidth can be randomly called and may destroy some layouts (see #346)



This should wiek
