### ISSUE TITLE
[bug] AddFont not working depending on scale factor on windows

### ISSUE THREAD

**Issue by 0xkalle** [AllenDang/giu#759]
### What happend?

When adding font in different sizes with `AddFont` to the FontAtlas, it is working fine on 100% Scale. On other Scales it is not working or partly working. e.g. on 125% no custom fonts work while on 150% some work.

Beside the example below I also made as simple as possible example repo: https://github.com/0xkalle/giu-font-test 

I also tried to run with master. But it is crashing (even the hello world example crashes)

### Code example

<details><summary><code>main.go</code></summary>

```golang
package main

import (
	g "github.com/AllenDang/giu"
)

var (
	datafont_16 *g.FontInfo
	datafont_24 *g.FontInfo
	datafont_32 *g.FontInfo
	datafont_48 *g.FontInfo
	datafont_64 *g.FontInfo
	datafont_72 *g.FontInfo
	datafont_96 *g.FontInfo
)

func loop() {
	g.SingleWindow().Layout(
		g.Label("0verlay Text 96").Font(datafont_96),
		g.Label("0verlay Text 72").Font(datafont_72),
		g.Label("0verlay Text 64").Font(datafont_64),
		g.Label("0verlay Text 48").Font(datafont_48),
		g.Label("0verlay Text 32").Font(datafont_32),
		g.Label("0verlay Text 24").Font(datafont_24),
		g.Label("0verlay Text 16").Font(datafont_16),
	)
}

func main() {
	wnd := g.NewMasterWindow("Font test", 600, 400, 0)
	datafont_16 = g.Context.FontAtlas.AddFont("robotomono-m.ttf", 16)
	datafont_24 = g.Context.FontAtlas.AddFont("robotomono-m.ttf", 24)
	datafont_32 = g.Context.FontAtlas.AddFont("robotomono-m.ttf", 32)
	datafont_48 = g.Context.FontAtlas.AddFont("robotomono-m.ttf", 48)
	datafont_64 = g.Context.FontAtlas.AddFont("robotomono-m.ttf", 64)
	datafont_72 = g.Context.FontAtlas.AddFont("robotomono-m.ttf", 72)
	datafont_96 = g.Context.FontAtlas.AddFont("robotomono-m.ttf", 96)

	wnd.Run(loop)
}
```

</details>

### To Reproduce

1. Set Scale in windows to 100 / 125 / 150 %
2. Run my demo
3. see the fonts in window.

Results are:
100%
![100](https://github.com/AllenDang/giu/assets/31923808/38415cea-311c-4c6f-9ba8-c4333190546d)

125%
![125](https://github.com/AllenDang/giu/assets/31923808/df81c778-58e4-4f58-8a76-b500c0b837f9)

150%
<img width="451" alt="150" src="https://github.com/AllenDang/giu/assets/31923808/46dd6b5e-b445-4b64-ab93-59559924a000">

### Version

(latest)

### OS

windows 10

**Comment by wxblue** [comment]
Use original key for extraFontMap in FontAtlasProsessor.go
```
        // Add extra fonts
	for _, fontInfo := range a.extraFonts {
		// Scale font size with DPI scale factor
		key := fontInfo.String()
		if runtime.GOOS == windows {
			fontInfo.size *= Context.GetPlatform().GetContentScale()
		}

		// Store imgui.Font for PushFont
		var f imgui.Font
		if len(fontInfo.fontByte) == 0 {
			f = fonts.AddFontFromFileTTFV(fontInfo.fontPath, fontInfo.size, imgui.DefaultFontConfig, ranges.Data())
		} else {
			f = fonts.AddFontFromMemoryTTFV(fontInfo.fontByte, fontInfo.size, imgui.DefaultFontConfig, ranges.Data())
		}

		a.extraFontMap[key] = &f
	}
```

**Comment by 0xkalle** [comment]
I'll try that later today. Thanks. :)

**Comment by 0xkalle** [comment]
Works. :) Is it worth it to make a PR for this or should it be fixed in the upcoming c-imgui version if still needed?

**Comment by gucio321** [comment]
idk, could you check if this issue still exists on master?

**Comment by 0xkalle** [comment]
I'll check. Last time I couldn't get it to run with master. I'll try again and report back. :)

**Comment by 0xkalle** [comment]
Still persists on master as well.

It also leads to this odd window that keeps getting bigger like mentioned in #155 . But I can see the fonts in the beginning and on 125% scaling they are not the fonts they should be and not in the right size.

Here is a screen recording:

https://github.com/AllenDang/giu/assets/31923808/a76bb72c-dddf-4c90-864d-4134d23c2ee3

**Comment by gucio321** [comment]
@0xkalle May I ask you to try again with v0.8.1?
The issue from your previous post was fixed in #810

**Comment by 0xkalle** [comment]
> @0xkalle May I ask you to try again with v0.8.1? The issue from your previous post was fixed in #810

"Grow to death" is gone. 👍 

Font sizes are not working like described in the initial post of the thread https://github.com/AllenDang/giu/issues/759#issue-2126893620

**Comment by 0xkalle** [comment]
@gucio321 does it make sence to test with 0.9.X again? :)

**Comment by gucio321** [comment]
Meh, not really. I think it's still a bug in giu unfortunately

**Comment by 0xkalle** [comment]
This error still persists. From the gui fonttest repo with 0.13.0

![Image](https://github.com/user-attachments/assets/7a826cee-f823-46cf-882c-8466f1c7ab47)

Still same result. I also updated the font test repo to 0.13.0.

@gucio321 is there any chance that this will be fixed somewhen?

**Comment by gucio321** [comment]
@0xkalle thank you for testing. Unfortunately I can't say anything about windows as I'm working on linux all the time and my windows is not dev-friendly atm...

If you'd like to debug this I'd really appreciate.

FIrst of all I'd check what this scale even is and whether without these lines it works better or something:

```go
                        if runtime.GOOS == windows {
                                xScale, _ := Context.backend.ContentScale()
                                fontInfo.size *= xScale
                        }
```
(This is FontAtlasProcessor.go:314 on master).
You can use `go mod vendor` in your test repo (should work with cimgui-go now)

**Comment by 0xkalle** [comment]
@gucio321 More than happy to help debuging it. :) I am just not into imgui enough to understand everything (maybe yet ;) ).

I'll check what you mentioned as soon as I have time and let you know what happens.

**Comment by 0xkalle** [comment]
@gucio321 checked it.

The lines you mention (at :324) do not have any effect. (I think because they only effect the default fonts.

same file on line :345 there are the same lines for the extra fonts. These have effect and if I remove these. It just works as expected I'd say. Expected in terms of: The fonts are loaded. They do not have the same size (because it is obviously not scaled to the discplay scale)

I added a simple log to print resulting sizes:
`fmt.Printf("Font %s, size: %.2f\n", fontInfo.fontName, fontInfo.size)`

If I leave the lines as is:
```
Font robotomono-m.ttf, size: 24.00
Font robotomono-m.ttf, size: 36.00
Font robotomono-m.ttf, size: 48.00
Font robotomono-m.ttf, size: 72.00
Font robotomono-m.ttf, size: 96.00
Font robotomono-m.ttf, size: 108.00
Font robotomono-m.ttf, size: 144.00
```
But the fonts are not displayed correctly then.

If I remove the lines:
```
Font robotomono-m.ttf, size: 16.00
Font robotomono-m.ttf, size: 24.00
Font robotomono-m.ttf, size: 32.00
Font robotomono-m.ttf, size: 48.00
Font robotomono-m.ttf, size: 64.00
Font robotomono-m.ttf, size: 72.00
Font robotomono-m.ttf, size: 96.00
```
The font sizes are not scales, but displayed in these sizes with the correct font type.

**Comment by 0xkalle** [comment]
Just let me know when I can help. :)

**Comment by gucio321** [comment]
okey, I can reproduce on linux (when I remove GOOS part). 
For some reason, if I modify the fontInfo.size anyhow, it doesn't actually change the size.

**Comment by 0xkalle** [comment]
I for now just use a local giu version and exclude the lines mentioned above. Yes, the font sizes do not adjust automatically, but in my usecase that is not important, because font sizes are adjusted by window size anyways.

**Comment by gucio321** [comment]
wtf is going on here (????) I'll need to use delve...
